In [1]:
import pandas as pd
from sklearn import preprocessing

In [2]:
data = pd.read_csv("../outputs/clean_houses.csv")

In [3]:
data.rename(columns={"Unnamed: 0":"index"},inplace=True)
data.set_index("index", inplace=True)
data.head()

,neighborhood_id,house_type_id,is_renewal_needed,is_new_development,sq_mt_built,n_rooms,n_bathrooms,floor,is_exterior,has_lift,has_parking,has_storage_room,has_terrace,has_balcony,has_pool,buy_price,buy_price_by_area,latitude,longitude
index,,,,,,,,,,,,,,,,,,,
0,"San Cristóbal, Villaverde(Madrid)",HouseType 1: Pisos,False,False,64.0,2,1.0,3,True,False,False,False,False,False,False,85000,1328,40.343263,-3.688352
1,"Los Ángeles, Villaverde(Madrid)",HouseType 1: Pisos,True,False,70.0,3,1.0,4,True,True,False,False,True,False,False,129900,1856,40.355109,-3.700105
2,"San Andrés, Villaverde(Madrid)",HouseType 1: Pisos,False,False,94.0,2,2.0,1,True,True,False,True,False,False,False,144247,1535,40.345539,-3.710970
3,"San Andrés, Villaverde(Madrid)",HouseType 1: Pisos,False,False,64.0,2,1.0,Bajo,True,True,False,True,False,False,False,109900,1717,40.345539,-3.710970
4,"Los Rosales, Villaverde(Madrid)",HouseType 1: Pisos,False,False,108.0,2,2.0,4,True,True,True,True,False,False,True,260000,2407,40.355841,-3.688399

In [4]:
def transf(column):

    le = preprocessing.LabelEncoder()
    data[column] = le.fit_transform(data[column])
    return data[column]

In [5]:
transf("is_renewal_needed")
transf("is_new_development")
transf("is_exterior")
transf("has_lift")
transf("has_parking")
transf("has_storage_room")
transf("has_terrace")
transf("has_balcony")
transf("has_pool")

index
0        0
1        0
2        0
3        0
4        1
        ..
17393    1
17394    1
17395    0
17396    1
17397    1
Name: has_pool, Length: 17398, dtype: int64

In [6]:
data.sq_mt_built.value_counts().head(300)

70.0     428
60.0     412
80.0     379
65.0     339
90.0     316
        ...
291.0      6
366.0      6
288.0      6
318.0      6
282.0      6
Name: sq_mt_built, Length: 300, dtype: int64

In [7]:
data = data.drop(data[data["buy_price"]>1200000].index)
data = data.drop(data[data["sq_mt_built"]>300].index)
data = data.drop(data[data["n_rooms"]>5].index)
data = data.drop(data[data["n_bathrooms"]>5].index)

In [8]:
data.reset_index()
data

,neighborhood_id,house_type_id,is_renewal_needed,is_new_development,sq_mt_built,n_rooms,n_bathrooms,floor,is_exterior,has_lift,has_parking,has_storage_room,has_terrace,has_balcony,has_pool,buy_price,buy_price_by_area,latitude,longitude
index,,,,,,,,,,,,,,,,,,,
0,"San Cristóbal, Villaverde(Madrid)",HouseType 1: Pisos,0,0,64.0,2,1.0,3,1,0,0,0,0,0,0,85000,1328,40.343263,-3.688352
1,"Los Ángeles, Villaverde(Madrid)",HouseType 1: Pisos,1,0,70.0,3,1.0,4,1,1,0,0,1,0,0,129900,1856,40.355109,-3.700105
2,"San Andrés, Villaverde(Madrid)",HouseType 1: Pisos,0,0,94.0,2,2.0,1,1,1,0,1,0,0,0,144247,1535,40.345539,-3.710970
3,"San Andrés, Villaverde(Madrid)",HouseType 1: Pisos,0,0,64.0,2,1.0,Bajo,1,1,0,1,0,0,0,109900,1717,40.345539,-3.710970
4,"Los Rosales, Villaverde(Madrid)",HouseType 1: Pisos,0,0,108.0,2,2.0,4,1,1,1,1,0,0,1,260000,2407,40.355841,-3.688399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17393,"Campo de las Naciones-Corralejos, Barajas(Madrid)",HouseType 1: Pisos,0,0,88.0,2,2.0,1,1,1,1,1,0,0,1,360000,4420,40.459749,-3.612738
17394,"Campo de las Naciones-Corralejos, Barajas(Madrid)",HouseType 1: Pisos,0,0,99.0,2,2.0,1,1,1,1,1,0,0,1,349000,3525,40.459749,-3.612738
17395,"Casco Histórico de Barajas, Barajas(Madrid)",HouseType 5: Áticos,0,0,78.0,2,2.0,4,1,1,1,1,0,0,0,350000,4487,40.479840,-3.580251
17396,"Campo de las Naciones-Corralejos, Barajas(Madrid)",HouseType 1: Pisos,0,0,96.0,2,2.0,3,1,1,1,1,0,0,1,425000,4427,40.459749,-3.612738
17397,"Campo de las Naciones-Corralejos, Barajas(Madrid)",HouseType 1: Pisos,0,0,175.0,4,2.0,Bajo,1,0,1,1,1,0,1,680000,3886,40.459749,-3.612738

In [9]:
# Aplicamos ahora get_dummies a la columna "house_type_id" y "floor".

data = pd.get_dummies(data, columns = ["house_type_id","floor"])

In [10]:
data.columns

Index(['neighborhood_id', 'is_renewal_needed', 'is_new_development',
       'sq_mt_built', 'n_rooms', 'n_bathrooms', 'is_exterior', 'has_lift',
       'has_parking', 'has_storage_room', 'has_terrace', 'has_balcony',
       'has_pool', 'buy_price', 'buy_price_by_area', 'latitude', 'longitude',
       'house_type_id_HouseType 1: Pisos', 'house_type_id_HouseType 4: Dúplex',
       'house_type_id_HouseType 5: Áticos', 'floor_1', 'floor_2', 'floor_3',
       'floor_4', 'floor_5', 'floor_6', 'floor_7', 'floor_8', 'floor_9',
       'floor_Bajo', 'floor_Entreplanta exterior',
       'floor_Entreplanta interior', 'floor_Semi-sótano exterior',
       'floor_Semi-sótano interior', 'floor_Sótano exterior',
       'floor_Sótano interior'],
      dtype='object')

In [11]:
data = data[['is_renewal_needed', 'is_new_development',
       'sq_mt_built', 'n_rooms', 'n_bathrooms', 'is_exterior', 'has_lift',
       'has_parking', 'has_storage_room', 'has_terrace', 'has_balcony',
       'has_pool', 'latitude', 'longitude',
       'house_type_id_HouseType 1: Pisos', 'house_type_id_HouseType 4: Dúplex',
       'house_type_id_HouseType 5: Áticos', 'floor_1', 'floor_2', 'floor_3',
       'floor_4', 'floor_5', 'floor_6', 'floor_7', 'floor_8', 'floor_9',
       'floor_Bajo', 'floor_Entreplanta exterior',
       'floor_Entreplanta interior', 'floor_Semi-sótano exterior',
       'floor_Semi-sótano interior', 'floor_Sótano exterior',
       'floor_Sótano interior', 'buy_price']]

### Iniciamos el análisis con H2O

In [12]:
import h2o
from h2o.estimators import H2ORandomForestEstimator

h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: java version "14.0.1" 2020-04-14; Java(TM) SE Runtime Environment (build 14.0.1+7); Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.8/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /var/folders/67/cftjwrk93ll2_6bwxqr4mkzc0000gn/T/tmphzosr0fc
  JVM stdout: /var/folders/67/cftjwrk93ll2_6bwxqr4mkzc0000gn/T/tmphzosr0fc/h2o_Javi_started_from_python.out
  JVM stderr: /var/folders/67/cftjwrk93ll2_6bwxqr4mkzc0000gn/T/tmphzosr0fc/h2o_Javi_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Europe/Madrid
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.1.3
H2O_cluster_version_age:    13 days
H2O_cluster_name:           H2O_from_python_Javi_e52ups
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.8.3 final
--------------------------  ------------------------------------------------------------------

In [13]:
h2train = h2o.H2OFrame(data)

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [14]:
columnas = [col for col in data.columns if col not in ["buy_price"]]

x = list(columnas)

y = "buy_price"

In [15]:
from h2o.automl import H2OAutoML

automl = H2OAutoML(max_runtime_secs=1200, sort_metric='RMSE')
automl.train(x, y, training_frame=h2train)
leader_board = automl.leaderboard
leader_board.head()

AutoML progress: |████████████████████████████████████████████████████████| 100%

model_id,rmse,mean_residual_deviance,mse,mae,rmsle
StackedEnsemble_AllModels_AutoML_20201012_093040,67218.4,4.51832e+09,4.51832e+09,42294.6,0.161015
StackedEnsemble_BestOfFamily_AutoML_20201012_093040,68229.8,4.6553e+09,4.6553e+09,43303.6,0.163188
XGBoost_grid__1_AutoML_20201012_093040_model_11,69813.7,4.87395e+09,4.87395e+09,44809.9,0.168754
GBM_4_AutoML_20201012_093040,70014.7,4.90206e+09,4.90206e+09,45059.6,0.167689
GBM_grid__1_AutoML_20201012_093040_model_3,70131.6,4.91844e+09,4.91844e+09,44573.9,0.169012
XGBoost_grid__1_AutoML_20201012_093040_model_5,70809.4,5.01397e+09,5.01397e+09,45192.9,0.171522
GBM_grid__1_AutoML_20201012_093040_model_1,70821.4,5.01567e+09,5.01567e+09,44380.6,0.172274
GBM_grid__1_AutoML_20201012_093040_model_6,70858.4,5.02092e+09,5.02092e+09,46043.6,0.170625
GBM_grid__1_AutoML_20201012_093040_model_8,71034.2,5.04585e+09,5.04585e+09,44996,0.170423
GBM_3_AutoML_20201012_093040,71060.6,5.04961e+09,5.04961e+09,46081,0.169298

In [23]:
from h2o.automl import H2OAutoML

automl = H2OAutoML(max_models=50, seed=1,max_runtime_secs=1800, sort_metric='RMSE')
automl.train(x, y, training_frame=h2train)

AutoML progress: |████████████████████████████████████████████████████████| 100%

In [17]:
leader_board = automl.leaderboard
leader_board.head()

model_id,rmse,mean_residual_deviance,mse,mae,rmsle
StackedEnsemble_AllModels_AutoML_20201012_095029,67079.7,4.49969e+09,4.49969e+09,41938.9,0.161122
StackedEnsemble_BestOfFamily_AutoML_20201012_095029,67740.3,4.58875e+09,4.58875e+09,42371.1,0.162997
XGBoost_grid__1_AutoML_20201012_095029_model_1,69654.3,4.85172e+09,4.85172e+09,44060.6,0.168834
GBM_grid__1_AutoML_20201012_095029_model_7,69913.8,4.88795e+09,4.88795e+09,44016,0.169202
XGBoost_grid__1_AutoML_20201012_095029_model_3,69960.4,4.89446e+09,4.89446e+09,44612.6,0.168482
GBM_4_AutoML_20201012_095029,70259.9,4.93646e+09,4.93646e+09,45153.4,0.167376
GBM_grid__1_AutoML_20201012_095029_model_9,70266.4,4.93736e+09,4.93736e+09,44807.5,0.168142
XGBoost_grid__1_AutoML_20201012_095029_model_2,70366.6,4.95146e+09,4.95146e+09,44776,0.169941
XGBoost_grid__1_AutoML_20201012_095029_model_6,71211.4,5.07107e+09,5.07107e+09,45532.9,0.173867
XGBoost_grid__1_AutoML_20201012_095029_model_10,71490.3,5.11086e+09,5.11086e+09,46447.3,0.172853